// Generated by tools/bump-cache.js — do not edit by hand.
// Read at runtime via the global `BUILD_INFO` (window scope).
var BUILD_INFO = {
  "commit": "5c303a1",
  "commitFull": "5c303a13a4e3b42f3f29a5b02e72054aa585bfdc",
  "builtAt": "2026-04-29T06:55:19.761Z"
};
