// Generated by tools/bump-cache.js — do not edit by hand.
// Read at runtime via the global `BUILD_INFO` (window scope).
var BUILD_INFO = {
  "commit": "4c9be71",
  "commitFull": "4c9be7121b1e4bafc9746fd62bcf2506b26a36ff",
  "builtAt": "2026-05-08T00:52:52.034Z"
};
