// Generated by tools/bump-cache.js — do not edit by hand.
// Read at runtime via the global `BUILD_INFO` (window scope).
var BUILD_INFO = {
  "commit": "28e9936",
  "commitFull": "28e9936e5a9b344248aa4ece149ec8fd5559a2a1",
  "builtAt": "2026-04-27T14:51:14.110Z"
};
